#!/usr/bin/env pwsh
# Setup Environment Files Script
# This script helps create the necessary .env files for development

Write-Host "`n╔══════════════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║     Environment Configuration Setup                          ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════════════════╝`n" -ForegroundColor Cyan

$webDir = "apps/web"

# Check if we're in the right directory
if (-not (Test-Path $webDir)) {
    Write-Host "❌ Error: Must be run from repository root" -ForegroundColor Red
    Write-Host "   Current directory: $(Get-Location)" -ForegroundColor Yellow
    exit 1
}

Write-Host "📁 Working directory: $webDir`n" -ForegroundColor Green

# Check if .env.example exists
if (-not (Test-Path "$webDir/.env.example")) {
    Write-Host "❌ Error: .env.example not found in $webDir" -ForegroundColor Red
    exit 1
}

# Function to create env file if it doesn't exist
function New-EnvFile {
    param(
        [string]$fileName,
        [string]$description,
        [string]$tasksPort,
        [string]$usersPort,
        [string]$envMode
    )
    
    $filePath = "$webDir/$fileName"
    
    if (Test-Path $filePath) {
        Write-Host "⚠️  $fileName already exists - skipping" -ForegroundColor Yellow
        return $false
    }
    
    $content = @"
# Environment Variables for $description
# Auto-generated by setup-env.ps1

# Backend API URLs
VITE_TASKS_API_URL=http://localhost:$tasksPort
VITE_USERS_API_URL=http://localhost:$usersPort

# App Configuration
VITE_APP_ENV=$envMode
VITE_APP_NAME=BLA Task Management System
VITE_ENABLE_DEBUG_LOGS=true
"@

    $content | Out-File -FilePath $filePath -Encoding UTF8
    Write-Host "✅ Created $fileName" -ForegroundColor Green
    return $true
}

Write-Host "🔧 Creating environment files...`n" -ForegroundColor Cyan

# Ask user what they want to set up
Write-Host "Select your development setup:" -ForegroundColor Yellow
Write-Host "  1. Docker only (recommended for full stack)" -ForegroundColor White
Write-Host "  2. Local development (APIs in Visual Studio/VS Code)" -ForegroundColor White
Write-Host "  3. Both (complete setup)" -ForegroundColor White
Write-Host "  4. Custom" -ForegroundColor White
Write-Host ""

$choice = Read-Host "Enter your choice (1-4)"

switch ($choice) {
    "1" {
        # Docker only
        Write-Host "`n📦 Setting up for Docker...`n" -ForegroundColor Cyan
        New-EnvFile ".env" "Docker (Default)" "5001" "5002" "docker"
        New-EnvFile ".env.test" "Docker Testing" "5001" "5002" "test"
        Write-Host "`n✅ Docker setup complete!" -ForegroundColor Green
        Write-Host "   Run: docker-compose up -d" -ForegroundColor White
        Write-Host "   Then: cd apps/web && npm run dev`n" -ForegroundColor White
    }
    "2" {
        # Local development
        Write-Host "`n🖥️  Setting up for local development...`n" -ForegroundColor Cyan
        New-EnvFile ".env.development" "Local Development" "5077" "5034" "development"
        New-EnvFile ".env" "Fallback" "5077" "5034" "development"
        Write-Host "`n✅ Local development setup complete!" -ForegroundColor Green
        Write-Host "   1. Start APIs from Visual Studio/VS Code" -ForegroundColor White
        Write-Host "   2. Run: cd apps/web && npm run dev`n" -ForegroundColor White
    }
    "3" {
        # Both
        Write-Host "`n🔧 Setting up complete environment...`n" -ForegroundColor Cyan
        New-EnvFile ".env" "Docker (Default)" "5001" "5002" "docker"
        New-EnvFile ".env.development" "Local Development" "5077" "5034" "development"
        New-EnvFile ".env.test" "Docker Testing" "5001" "5002" "test"
        Write-Host "`n✅ Complete setup done!" -ForegroundColor Green
        Write-Host "   For Docker: docker-compose up -d && cd apps/web && npm run dev" -ForegroundColor White
        Write-Host "   For Local: Start APIs in VS, then cd apps/web && npm run dev`n" -ForegroundColor White
    }
    "4" {
        # Custom
        Write-Host "`n🎨 Custom setup...`n" -ForegroundColor Cyan
        Write-Host "Copy .env.example and edit manually:" -ForegroundColor White
        Write-Host "   cp apps/web/.env.example apps/web/.env" -ForegroundColor Gray
        Write-Host "   code apps/web/.env`n" -ForegroundColor Gray
    }
    default {
        Write-Host "`n❌ Invalid choice. Exiting.`n" -ForegroundColor Red
        exit 1
    }
}

# Show current files
Write-Host "`n📋 Current .env files in $webDir/:" -ForegroundColor Cyan
Get-ChildItem "$webDir/.env*" -ErrorAction SilentlyContinue | 
    Select-Object Name, @{Name="Size";Expression={$_.Length}}, LastWriteTime |
    Format-Table -AutoSize

Write-Host "📖 For more information, see: $webDir/ENV_SETUP.md`n" -ForegroundColor Gray
Write-Host "✨ Done!`n" -ForegroundColor Green
