#!/bin/bash
# Setup Environment Files Script (Linux/Mac)
# This script helps create the necessary .env files for development

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     Environment Configuration Setup                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

WEB_DIR="apps/web"

# Check if we're in the right directory
if [ ! -d "$WEB_DIR" ]; then
    echo "❌ Error: Must be run from repository root"
    echo "   Current directory: $(pwd)"
    exit 1
fi

echo "📁 Working directory: $WEB_DIR"
echo ""

# Check if .env.example exists
if [ ! -f "$WEB_DIR/.env.example" ]; then
    echo "❌ Error: .env.example not found in $WEB_DIR"
    exit 1
fi

# Function to create env file
create_env_file() {
    local file_name=$1
    local description=$2
    local tasks_port=$3
    local users_port=$4
    local env_mode=$5
    
    local file_path="$WEB_DIR/$file_name"
    
    if [ -f "$file_path" ]; then
        echo "⚠️  $file_name already exists - skipping"
        return 1
    fi
    
    cat > "$file_path" << EOF
# Environment Variables for $description
# Auto-generated by setup-env.sh

# Backend API URLs
VITE_TASKS_API_URL=http://localhost:$tasks_port
VITE_USERS_API_URL=http://localhost:$users_port

# App Configuration
VITE_APP_ENV=$env_mode
VITE_APP_NAME=BLA Task Management System
VITE_ENABLE_DEBUG_LOGS=true
EOF

    echo "✅ Created $file_name"
    return 0
}

echo "🔧 Creating environment files..."
echo ""

# Ask user what they want to set up
echo "Select your development setup:"
echo "  1. Docker only (recommended for full stack)"
echo "  2. Local development (APIs in Visual Studio/VS Code)"
echo "  3. Both (complete setup)"
echo "  4. Custom"
echo ""
read -p "Enter your choice (1-4): " choice

case $choice in
    1)
        # Docker only
        echo ""
        echo "📦 Setting up for Docker..."
        echo ""
        create_env_file ".env" "Docker (Default)" "5001" "5002" "docker"
        create_env_file ".env.test" "Docker Testing" "5001" "5002" "test"
        echo ""
        echo "✅ Docker setup complete!"
        echo "   Run: docker-compose up -d"
        echo "   Then: cd apps/web && npm run dev"
        echo ""
        ;;
    2)
        # Local development
        echo ""
        echo "🖥️  Setting up for local development..."
        echo ""
        create_env_file ".env.development" "Local Development" "5077" "5034" "development"
        create_env_file ".env" "Fallback" "5077" "5034" "development"
        echo ""
        echo "✅ Local development setup complete!"
        echo "   1. Start APIs from Visual Studio/VS Code"
        echo "   2. Run: cd apps/web && npm run dev"
        echo ""
        ;;
    3)
        # Both
        echo ""
        echo "🔧 Setting up complete environment..."
        echo ""
        create_env_file ".env" "Docker (Default)" "5001" "5002" "docker"
        create_env_file ".env.development" "Local Development" "5077" "5034" "development"
        create_env_file ".env.test" "Docker Testing" "5001" "5002" "test"
        echo ""
        echo "✅ Complete setup done!"
        echo "   For Docker: docker-compose up -d && cd apps/web && npm run dev"
        echo "   For Local: Start APIs in VS, then cd apps/web && npm run dev"
        echo ""
        ;;
    4)
        # Custom
        echo ""
        echo "🎨 Custom setup..."
        echo ""
        echo "Copy .env.example and edit manually:"
        echo "   cp apps/web/.env.example apps/web/.env"
        echo "   nano apps/web/.env"
        echo ""
        ;;
    *)
        echo ""
        echo "❌ Invalid choice. Exiting."
        echo ""
        exit 1
        ;;
esac

# Show current files
echo ""
echo "📋 Current .env files in $WEB_DIR/:"
ls -lh "$WEB_DIR/.env"* 2>/dev/null || echo "No .env files found"
echo ""

echo "📖 For more information, see: $WEB_DIR/ENV_SETUP.md"
echo ""
echo "✨ Done!"
echo ""
